### PR TITLE
Dwc animals mapping

### PR DESCRIPTION
**Pull request by LienReyserhove**
This PR contains the full mapping of the etn metadata, which includes information from the animal and tags table from the [ETN application](http://www.lifewatch.be/etn/). A detailed scheme representing the structure and terms of the mapping can be found [here](https://github.com/inbo/etn-occurrences/issues/31).

While reviewing, please tick off the boxes to indicate the specific term/characteristic is OK
Note: for many of the terms/characterstic, there are still outstanding issues. Whenever this is the case, a reference to these issues is made in the .Rmd file.

### Capture event
- [x] eventID: full urn
- [x] samplingProtocol
- [x] eventDate
- [x] locality
- [x] decimalLatitude: 5 decimals
- [x] decimalLongitude: 5 decimals

### Surgery event
- [x] eventID: full urn
- [x] samplingProtocol
- [ ] eventDate: see https://github.com/inbo/etn-occurrences/issues/43
- [x] locality
- [ ] decimalLatitude: 5 decimals: see https://github.com/inbo/etn-occurrences/issues/43
- [ ] decimalLongitude: 5 decimals: see https://github.com/inbo/etn-occurrences/issues/43

### Release event
- [x] eventID: full urn
- [x] samplingProtocol: `release`
- [x] eventDate
- [x] locality
- [x] decimalLatitude: 5 decimals
- [x] decimalLongitude: 5 decimals

### Static event Core terms:

metadata:

- [x] type: `Event`, not `event`
- [x] modified: how much can we trust this?
- [x] language
- [x] license
- [ ] rightsHolder: see https://github.com/inbo/etn/issues/69			
- [ ] institutionCode: see https://github.com/inbo/etn/issues/69
- [ ] datasetID
- [x] datasetName	
- [x] basisOfRecord: Capitalize

Other terms:

- [x] geodeticDatum: leave empty for empty coordinates
- [x] coordinateUncertaintyInMeters: leave empty for empty coordinates

## Create occurrence extension

As this is a 1:1 mapping with the event core, the occurrence information was added to the event core

- [x] occurrenceID: full urn
- [ ] recordedBy
- [x] scientificName
- [x] kingdom
- [x] phylum
- [x] vernacularName
- [x] taxonRank

### EMoF associated with capture occurrence

- [x] Length
- [x] Weight
- [x] Life stage
- [x] Age
- [x] Sex
- [x] Origin
- [x] eventID: full urn
- [x] occurrenceID: full urn

## EMoF associated with surgery event

Animal information:
- [x] Anaesthetic
- [x] Post operation holding period

Tag information:
- [x] Tag full id
- [x] Tag serial number
- [x] Telemetry type
- [x] Tag model
- [x] Tag sensor type
- [x] Tag status
- [x] Tag estimated lifetime
- [x] Tag emission frequency

Other terms:
- [x] eventID: full urn
- [x] occurrenceID: full urn

### CODE REVIEW

**Comment by peterdesmet** [comment]
- [x] emof contains row numbers, should be removed
- [x] `2015_phd_verhelst:2160:event-surgery` contains an empty emof

**Review by peterdesmet — CHANGES_REQUESTED** [review]
Nice work! I've checked off everything that is OK and updated the Rmd. Can you:

- [x] Check if Rmd still runs?
- [x] Check empty emof values
- [x] Address https://github.com/inbo/etn-occurrences/pull/52#issuecomment-509175132

**Comment by LienReyserhove** [comment]
For some reason, this code does not work:

>write_csv(event, here("data", "processed", "event.csv"), na = "")

but this works:
> write_csv(event, "../data/processed/event.csv", na = "")

To be able to integrate the required corrections, I changed this code to the working version for now. Of course we can change this again afterwards, but I'm not sure what's going wrong.

**Comment by peterdesmet** [comment]
Fine to leave it like that, maybe related to where RProj file is located.

**Comment by LienReyserhove** [comment]
Thanks for the review, I integrated all requested changes by @peterdesmet 
Some issues related to adaptations in the database are still open:
- #41 
- #42 
- #43 
- #45 
- #46 

However, these issues will probably not get resolved in the near future as @fwaumans will be absent up to September. I suggest that we publish the dataset without these adaptations anyway and update the reviewed version later.

@damianooldoni if you could integrate the requested changes in https://github.com/inbo/etn/issues/69?

**Pull request merged**
